### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by nickrox** [airbnb/caravel#1048]
Getting the following error after restarting caravel and login with user created earlier.
```
Traceback (most recent call last):
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask_appbuilder/security/views.py", line 377, in login
    user = self.appbuilder.sm.auth_user_db(form.username.data, form.password.data)
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 515, in auth_user_db
    elif check_password_hash(user.password, password):
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/werkzeug/security.py", line 124, in check_password_hash
    return safe_str_cmp(_hash_internal(method, salt, password), hashval)
  File "/opt/SP/dm_store/anaconda2/lib/python2.7/site-packages/werkzeug/security.py", line 48, in safe_str_cmp
    if len(a) != len(b):
TypeError: object of type 'NoneType' has no len()
```

**Comment by xrmx** [comment]
What version of caravel is this? How have you installed things?

**Comment by nickrox** [comment]
Running Caravel 0.10 with Postresql 9.5 on CentOS Linux release 7.2.1511 (Core)
Python 2.7

**Comment by nickrox** [comment]
just reinstalled caravel using pip and pointed old caravel.db in caravel_config.py. It worked and I am able to login . 
```
#uninstall
pip uninstall caravel
#install
pip install caravel

```
