### ISSUE TITLE
Can't create word cloud

### ISSUE THREAD

**Issue by spektom** [airbnb/caravel#106]
Every try to draw word cloud ends up with this exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/panoramix/utils.py", line 202, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/panoramix/views.py", line 395, in explore
    payload = obj.get_json()
  File "/usr/local/lib/python2.7/dist-packages/panoramix/viz.py", line 204, in get_json
    'data': json.loads(self.get_json_data()),
  File "/usr/local/lib/python2.7/dist-packages/panoramix/viz.py", line 377, in get_json_data
    df.columns = ['text', 'size']
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 2161, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/src/properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas/lib.c:42548)
    
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 413, in _set_axis
    self._data.set_axis(axis, labels)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 2219, in set_axis
    'new values have %d elements' % (old_len, new_len))
ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements
```

**Comment by mistercrunch** [comment]
I think this is fixed, please reopen if that's not the case
