### ISSUE TITLE
Exception when using World Map Slice

### ISSUE THREAD

**Issue by maver1ck** [airbnb/caravel#1135]
When choosing World Map Slice, I'm getting this exception.
Unfortunatelly exception isn't pass to UI, so query is running infinitely.
 
```
2016-09-19 12:05:28,571:ERROR:root:Wrong number of items passed 2, placement implies 1
Traceback (most recent call last):
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/indexes/base.py", line 1945, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'm1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/core/internals.py", line 3415, in set
    loc = self.items.get_loc(item)
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'm1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbrynski/.local/lib/python3.4/site-packages/caravel/views.py", line 827, in explore
    payload = obj.get_json()
  File "/home/mbrynski/.local/lib/python3.4/site-packages/caravel/viz.py", line 294, in get_json
    'data': self.get_data(),
  File "/home/mbrynski/.local/lib/python3.4/site-packages/caravel/viz.py", line 1481, in get_data
    ndf['m1'] = df[metric]
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/core/frame.py", line 2357, in __setitem__
    self._set_item(key, value)
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/core/frame.py", line 2424, in _set_item
    NDFrame._set_item(self, key, value)
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/core/generic.py", line 1464, in _set_item
    self._data.set(key, value)
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/core/internals.py", line 3418, in set
    self.insert(len(self.items), item, value)
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/core/internals.py", line 3519, in insert
    placement=slice(loc, loc + 1))
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/core/internals.py", line 2518, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/home/mbrynski/.local/lib/python3.4/site-packages/pandas/core/internals.py", line 90, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 2, placement implies 1
[2016-09-19 12:05:37 +0000] [1197] [INFO] Handling signal: winch
```

**Comment by xrmx** [comment]
Which version is this? If that's not master possibly it has already been fixed there.

**Comment by maver1ck** [comment]
Official from pip (so I assume it's 0.10.0)

**Comment by xrmx** [comment]
@maver1ck could you please try to reproduce in master please? If that's a production instance don't upgrade there though :)

**Comment by maver1ck** [comment]
Yep.
Is there an instruction how to install master ?
pip install git+https://github.com/airbnb/caravel/ + js_build.sh ?
Something more ?

**Comment by xrmx** [comment]
https://github.com/airbnb/caravel/blob/master/docs/installation.rst#making-your-own-build

**Comment by maver1ck** [comment]
Got this.
OK. The bug was repaired.
I think that by this commit.
https://github.com/airbnb/caravel/commit/3c92ba9bd57f412e1ebf7f610c1b7a630c0ba53c

**Comment by xrmx** [comment]
Cool, closing then.

**Comment by maver1ck** [comment]
Any ETA of next version of Caravel so ?

**Comment by xrmx** [comment]
@maver1ck if they are not already reported yes, also PR even more welcome :)

**Comment by maver1ck** [comment]
@xrmx 
I'd like to contribute but unfortunatelly I'm rather backend developer and I don't have experience with JS and react.
Do you have some easy backend tasks ?

**Comment by xrmx** [comment]
@maver1ck #1141 is probably easy to fix as some variable is used but not defined, maybe a typo?
