### ISSUE TITLE
Error upgrading to 0.11.0

### ISSUE THREAD

**Issue by jwthomp** [airbnb/caravel#1297]
I attempted to migrate my sqlite database to 0.11 and am having some problems. The first was needing to use the `caravel db stamp f162a1dea4c4` work around. I then performed a `caravel db upgrade` 

The last bits of the upgrade log show a few warnings:

```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade f162a1dea4c4 -> ad82a75afd82, Update models to support storing the queries.
/usr/lib/python3.5/site-packages/alembic/util/messaging.py:69: UserWarning: Skipping unsupported ALTER for creation of implicit constraint
  warnings.warn(msg)
INFO  [alembic.runtime.migration] Running upgrade ad82a75afd82 -> 3c3ffe173e4f, add_sql_string_to_table
INFO  [alembic.runtime.migration] Running upgrade 3c3ffe173e4f -> 41f6a59a61f2, database options for sql lab
INFO  [alembic.runtime.migration] Running upgrade 41f6a59a61f2 -> 4500485bde7d, allow_run_sync_async
INFO  [alembic.runtime.migration] Running upgrade 4500485bde7d -> 65903709c321, allow_dml
INFO  [alembic.runtime.migration] Running upgrade 41f6a59a61f2 -> 33d996bcc382
INFO  [alembic.runtime.migration] Running upgrade 33d996bcc382, 65903709c321 -> b347b202819b, empty message
INFO  [alembic.runtime.migration] Running upgrade b347b202819b -> 5e4a03ef0bf0, Add access_request table to manage requests to access datastores.
INFO  [alembic.runtime.migration] Running upgrade 5e4a03ef0bf0 -> eca4694defa7, sqllab_setting_defaults
INFO  [alembic.runtime.migration] Running upgrade eca4694defa7 -> ab3d66c4246e, add_cache_timeout_to_druid_cluster
INFO  [alembic.runtime.migration] Running upgrade eca4694defa7 -> 3b626e2a6783, Sync DB with the models.py.
WARNI [root] No such constraint: 'slices_ibfk_1'
WARNI [root] Constraint must have a name
WARNI [root] No such index: 'table_name'
INFO  [alembic.runtime.migration] Running upgrade 3b626e2a6783, ab3d66c4246e -> ef8843b41dac, empty message
```

I am able to get onto my caravel instance and see a list of dashboard. However if I look at any tables or slices, I see the following error 
```
(sqlite3.OperationalError) no such column: sql_metrics.d3format [SQL: 'SELECT 
sql_metrics.created_on AS sql_metrics_created_on, sql_metrics.changed_on AS 
sql_metrics_changed_on, sql_metrics.id AS sql_metrics_id, sql_metrics.metric_name AS 
sql_metrics_metric_name, sql_metrics.verbose_name AS sql_metrics_verbose_name, 
sql_metrics.metric_type AS sql_metrics_metric_type, sql_metrics.table_id AS 
sql_metrics_table_id, sql_metrics.expression AS sql_metrics_expression, sql_metrics.description 
AS sql_metrics_description, sql_metrics.is_restricted AS sql_metrics_is_restricted, 
sql_metrics.d3format AS sql_metrics_d3format, sql_metrics.changed_by_fk AS 
sql_metrics_changed_by_fk, sql_metrics.created_by_fk AS sql_metrics_created_by_fk \n
FROM sql_metrics \nWHERE ? = sql_metrics.table_id'] [parameters: (19,)]
```

Any thoughts on what I might do to properly migrate from 0.10.0 to 0.11.0? Please let me know if I can provide any additional information and I will happily do so.

**Comment by kingo55** [comment]
Ran into this problem myself... albeit a slightly different flavour and am running MariaDB. 

Not sure how easy it is to query/update SQLite3 but doing this might help: 

https://github.com/amancevice/caravel/issues/14

**Comment by jwthomp** [comment]
@kingo55 Thank you for the pointer. I've tried that but am still having a similar issue. First for others, sqlite3 does not support alter removing columns, so I had to create a new table, copy the data over, remove the old table, then move the new table back by doing the following:

```
CREATE TABLE "table_columns_new" (
created_on DATETIME NOT NULL,
changed_on DATETIME NOT NULL,
id INTEGER NOT NULL,
table_id INTEGER,
column_name VARCHAR(255),
is_dttm BOOLEAN,
is_active BOOLEAN,
type VARCHAR(32),
groupby BOOLEAN,
count_distinct BOOLEAN,
sum BOOLEAN,
max BOOLEAN,
min BOOLEAN,
filterable BOOLEAN,
description TEXT,
created_by_fk INTEGER,
changed_by_fk INTEGER,
expression TEXT,
verbose_name VARCHAR(1024),
PRIMARY KEY (id),
CHECK (is_dttm IN (0, 1)),
CHECK (is_active IN (0, 1)),
CHECK (groupby IN (0, 1)),
CHECK (count_distinct IN (0, 1)),
CHECK (sum IN (0, 1)),
CHECK (max IN (0, 1)),
CHECK (min IN (0, 1)),
CHECK (filterable IN (0, 1)),
FOREIGN KEY(created_by_fk) REFERENCES ab_user (id),
FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id),
FOREIGN KEY(table_id) REFERENCES tables (id)
);

insert into table_columns_new select created_on, changed_on, id, table_id, column_name, is_dttm, is_active, type, groupby, count_distinct, sum, max, min, filterable, description, created_by_fk, changed_by_fk, expression, verbose_name from table_columns;

drop table table_columns;

alter table table_columns_new rename to table_columns;
```

I then did a `caravel db upgrade` and a `caravel init`

The init gives me the following error: 

```
2016-10-11 14:57:05,082:INFO:root:Creating database reference
2016-10-11 14:57:05,087:INFO:root:sqlite:////home/caravel/db/caravel.db
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: sql_metrics.d3format

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/caravel", line 155, in <module>
    manager.run()
  File "/usr/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/bin/caravel", line 64, in init
    utils.init(caravel)
  File "/usr/lib/python3.5/site-packages/caravel/utils.py", line 295, in init
    init_metrics_perm(caravel)
  File "/usr/lib/python3.5/site-packages/caravel/utils.py", line 312, in init_metrics_perm
    metrics += list(db.session.query(model).all())
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2613, in all
    return list(self)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: sql_metrics.d3format [SQL: 'SELECT sql_metrics.created_on AS sql_metrics_created_on, sql_metrics.changed_on AS sql_metrics_changed_on, sql_metrics.id AS sql_metrics_id, sql_metrics.metric_name AS sql_metrics_metric_name, sql_metrics.verbose_name AS sql_metrics_verbose_name, sql_metrics.metric_type AS sql_metrics_metric_type, sql_metrics.table_id AS sql_metrics_table_id, sql_metrics.expression AS sql_metrics_expression, sql_metrics.description AS sql_metrics_description, sql_metrics.is_restricted AS sql_metrics_is_restricted, sql_metrics.d3format AS sql_metrics_d3format, sql_metrics.changed_by_fk AS sql_metrics_changed_by_fk, sql_metrics.created_by_fk AS sql_metrics_created_by_fk \nFROM sql_metrics']
```

In app if I try to look at a table I get the following error (as part of a stack trace):

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: table_columns.python_date_format

[Not included stack trace, available upon request]

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: 
table_columns.python_date_format [SQL: 'SELECT table_columns.created_on AS 
table_columns_created_on, table_columns.changed_on AS table_columns_changed_on, 
table_columns.id AS table_columns_id, table_columns.table_id AS table_columns_table_id, 
table_columns.column_name AS table_columns_column_name, table_columns.verbose_name AS 
table_columns_verbose_name, table_columns.is_dttm AS table_columns_is_dttm, 
table_columns.is_active AS table_columns_is_active, table_columns.type AS table_columns_type, 
table_columns.groupby AS table_columns_groupby, table_columns.count_distinct AS 
table_columns_count_distinct, table_columns.sum AS table_columns_sum, table_columns.max AS 
table_columns_max, table_columns.min AS table_columns_min, table_columns.filterable AS 
table_columns_filterable, table_columns.expression AS table_columns_expression, 
table_columns.description AS table_columns_description, table_columns.python_date_format AS 
table_columns_python_date_format, table_columns.database_expression AS 
table_columns_database_expression, table_columns.changed_by_fk AS 
table_columns_changed_by_fk, table_columns.created_by_fk AS table_columns_created_by_fk 
\nFROM table_columns']
```

If I look at any dashboard I see the following where any slice should be:

```
(sqlite3.OperationalError) no such column: sql_metrics.d3format [SQL: 'SELECT 
sql_metrics.created_on AS sql_metrics_created_on, sql_metrics.changed_on AS 
sql_metrics_changed_on, sql_metrics.id AS sql_metrics_id, sql_metrics.metric_name AS 
sql_metrics_metric_name, sql_metrics.verbose_name AS sql_metrics_verbose_name, 
sql_metrics.metric_type AS sql_metrics_metric_type, sql_metrics.table_id AS 
sql_metrics_table_id, sql_metrics.expression AS sql_metrics_expression, sql_metrics.description 
AS sql_metrics_description, sql_metrics.is_restricted AS sql_metrics_is_restricted, 
sql_metrics.d3format AS sql_metrics_d3format, sql_metrics.changed_by_fk AS 
sql_metrics_changed_by_fk, sql_metrics.created_by_fk AS sql_metrics_created_by_fk \nFROM 
sql_metrics \nWHERE ? = sql_metrics.table_id'] [parameters: (19,)]
```

**Comment by jwthomp** [comment]
update: By going through the above process, but omitting the `caravel db stamp f162a1dea4c4` I get much further. Everything seems ok, except that all of tables are saying that the tables don't exist in the database. Looking into that now.

**Comment by jwthomp** [comment]
It looks like the issue is that I have to set the Datetime Format on my temporal columns again as otherwise no records show up.

I'll mark this closed now.

**Comment by mistercrunch** [comment]
@jwthomp what was the rational for stamping `f162a1dea4c4`? Looks like this resulted in skipping needed migrations.

**Comment by mistercrunch** [comment]
btw I wouldn't worry about the warning, it's coming from a db migration script

**Comment by jwthomp** [comment]
@mistercrunch My recollection is that when I was first trying to fix this I was seeing the alter error in https://github.com/airbnb/caravel/issues/817 so I tried that fix.

I'm guessing I misread the error.
