### ISSUE TITLE
Integer filter values result in error for Boxplot visualizations

### ISSUE THREAD

**Issue by ananya77041** [airbnb/caravel#1441]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the caravel logs for python stacktraces and included it here as text if any

2016-10-27 00:05:55,609:ERROR:root:argument of type 'int' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/caravel/views.py", line 1183, in explore
    viz_obj.get_json(),
  File "/usr/local/lib/python2.7/dist-packages/caravel/viz.py", line 318, in get_json
    'data': self.get_data(),
  File "/usr/local/lib/python2.7/dist-packages/caravel/viz.py", line 816, in get_data
    df = self.get_df()
  File "/usr/local/lib/python2.7/dist-packages/caravel/viz.py", line 737, in get_df
    df = super(BoxPlotViz, self).get_df(query_obj)
  File "/usr/local/lib/python2.7/dist-packages/caravel/viz.py", line 153, in get_df
    query_obj = self.query_obj()
  File "/usr/local/lib/python2.7/dist-packages/caravel/viz.py", line 271, in query_obj
    'filter': self.query_filters(),
  File "/usr/local/lib/python2.7/dist-packages/caravel/viz.py", line 225, in query_filters
    vals = ["'{}'".format(x) if "," in x else x for x in vals]
TypeError: argument of type 'int' is not iterable

- [ ] I have reproduced the issue with at least the latest released version of caravel
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Caravel version
0.11.0

### Expected results
After selecting an INTEGER type value from a Filter box dropdown selector, any Boxplot type slice to be impacted by that filter is correctly filtered.

### Actual results
After selecting an INTEGER type value from a Filter box dropdown selector, any Boxplot type slice to be impacted by that filter errors out with "TypeError: argument of type 'init' is not iterable".

### Steps to reproduce
1. Set up a datasource and table with at least 1 INTEGER typed column
2. Create Boxplot visualization and Filter box slices using the INTEGER column, and create a dashboard from these slices
3. Attempt to use integer filter. Encounter error

**Comment by mwullink** [comment]
I am having these same issue with 0.11.0. 
Is there a workaround?

**Comment by ananya77041** [comment]
@mwullink Workaround I've been using so far is to cast the integer column as another type such as varchar in the table configuration. Works just fine for filtering purposes.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 536 days. Feel free to comment and request for this issue to be reopened.
