### ISSUE TITLE
caravel/tasks.py ?

### ISSUE THREAD

**Issue by wyndhblb** [airbnb/caravel#1468]
Seems it got removed in this commit https://github.com/airbnb/caravel/pull/974, not sure if it was on purpose or not 

Let me know if i'm totally missing something.

Thanks

### Caravel version

master branch

### Expected results

`caravel worker`

should fire up some async workers

caravel/tasks.py ? seems to have disappeared 

### Actual results
```
Starting SQL Celery worker.
Celery broker url:
redis://caravel-redis:6379/0
Traceback (most recent call last):
  File "/usr/local/bin/caravel", line 155, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/bin/caravel", line 151, in worker
    c_worker.run(**options)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 121, in import_default_modules
    tuple(maybe_list(self.app.conf.CELERY_INCLUDE))
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 103, in import_task_module
    return self.import_from_cwd(module)
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 112, in import_from_cwd
    package=package,
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 106, in import_module
    return importlib.import_module(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named tasks
```

### Steps to reproduce

just run `caravel worker`

**Comment by bkyryliuk** [comment]
@wyndhblb , module is called now `sql_lab`.
Caravel worker works on` master` and `airbnb_prod` branches.

Please change `CELERY_IMPORTS = ('caravel.tasks', )` to CELERY_IMPORTS = ('caravel.sql_lab', )

**Comment by wyndhblb** [comment]
Much thanks  .. figured i was missing something.
