### ISSUE TITLE
build Caravel from sources error

### ISSUE THREAD

**Issue by wo8000** [airbnb/caravel#1555]
### Caravel version
0.12/0.11

### nodejs version
npm 3.9.5
node v6.2.2

### Steps to reproduce
cd $CARAVEL_HOME/caravel/assets
sudo npm install  --results ok
sudo npm run prod --results error

###results
sudo npm run prod
......
Condition always false [./~/.0.13.1@style-loader!./~/.0.23.1@css-loader!./stylesheets/welcome.css:10,0]
Dropping unreachable code [./~/.0.13.1@style-loader!./~/.0.23.1@css-loader!./stylesheets/welcome.css:12,0]
Side effects in initialization of unused variable update [./~/.0.13.1@style-loader!./~/.0.23.1@css-loader!./stylesheets/welcome.css:7,0]

ERROR in ./~/.1.7.2@react-map-gl/src/overlays/scatterplot.react.js
Module parse failed: /data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.1.7.2@react-map-gl/src/overlays/scatterplot.react.js Unexpected token (112:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (112:6)
    at Parser.pp$4.raise (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:839:33)
    at Parser.pp$1.parseStatement (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:699:34)
    at Parser.pp$1.parseBlock (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:2105:24)
    at Parser.pp$3.parseMethod (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:2075:10)
    at Parser.pp$1.parseClassMethod (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1137:25)
    at Parser.pp$1.parseClass (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1118:14)
    at Parser.pp$3.parseExprAtom (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1813:19)
    at Parser.pp$3.parseExprSubscripts (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1597:21)
    at Parser.pp$1.parseExport (/data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.3.3.0@acorn/dist/acorn.js:1164:23)
 @ ./visualizations/mapbox.jsx 23:24-81

ERROR in ./~/.1.0.0@mapbox-gl-shaders/index.js
Module not found: Error: Cannot resolve module 'fs' in /data/caravel-airbnb_prod.0.11.0.6/caravel/assets/node_modules/.1.0.0@mapbox-gl-shaders
 @ ./~/.1.0.0@mapbox-gl-shaders/index.js 1:9-22

**Comment by wyanjun** [comment]
I also got this error when run caravel/assets/js_build.sh.

**Comment by xrmx** [comment]
Dup of #1533
