### ISSUE TITLE
Installation Error on Ubuntu

### ISSUE THREAD

**Issue by silverstone1903** [airbnb/caravel#233]
Hey everyone. I couldn't install caravel with pip on Ubuntu 14.04 x64. Here is the log;

```
Requirement already satisfied (use --upgrade to upgrade): caravel in /usr/local/lib/python2.7/dist-packages/caravel-0.8.4-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): alembic>=0.8.5,<0.9.0 in /usr/local/lib/python2.7/dist-packages (from caravel)
Downloading/unpacking cryptography>=1.1.1,<2.0.0 (from caravel)
  Downloading cryptography-1.3.1.tar.gz (383kB): 383kB downloaded
  Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Requirement already satisfied (use --upgrade to upgrade): flask-appbuilder>=1.6.0,<2.0.0 in /usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.6.0-py2.7.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-cache>=0.13.1,<0.14.0 in /usr/local/lib/python2.7/dist-packages/Flask_Cache-0.13.1-py2.7.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-migrate>=1.5.1,<2.0.0 in /usr/local/lib/python2.7/dist-packages/Flask_Migrate-1.8.0-py2.7.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-script>=2.0.5,<3.0.0 in /usr/local/lib/python2.7/dist-packages/Flask_Script-2.0.5-py2.7.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-sqlalchemy==2.0.0 in /usr/local/lib/python2.7/dist-packages/Flask_SQLAlchemy-2.0-py2.7.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-testing>=0.4.2,<0.5.0 in /usr/local/lib/python2.7/dist-packages/Flask_Testing-0.4.2-py2.7.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask>=0.10.1,<1.0.0 in /usr/lib/python2.7/dist-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): humanize>=0.5.1,<0.6.0 in /usr/local/lib/python2.7/dist-packages/humanize-0.5.1-py2.7.egg (from caravel)
Downloading/unpacking gunicorn>=19.3.0,<20.0.0 (from caravel)
  Downloading gunicorn-19.4.5-py2.py3-none-any.whl (112kB): 112kB downloaded
Requirement already satisfied (use --upgrade to upgrade): markdown>=2.6.2,<3.0.0 in /usr/local/lib/python2.7/dist-packages/Markdown-2.6.6-py2.7.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9,<2 in /usr/local/lib/python2.7/dist-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): pandas==0.18.0 in /usr/local/lib/python2.7/dist-packages/pandas-0.18.0-py2.7-linux-x86_64.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): parsedatetime==2.0.0 in /usr/local/lib/python2.7/dist-packages/parsedatetime-2.0-py2.7.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): pydruid>=0.2.2,<0.3 in /usr/local/lib/python2.7/dist-packages/pydruid-0.2.3-py2.7.egg (from caravel)
Downloading/unpacking python-dateutil>=2.4.2,<3.0.0 (from caravel)
  Downloading python_dateutil-2.5.2-py2.py3-none-any.whl (201kB): 201kB downloaded
Downloading/unpacking requests>=2.7.0,<3.0.0 (from caravel)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB): 501kB downloaded
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy>=1.0.12,<2.0.0 in /usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.12-py2.7-linux-x86_64.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy-utils>=0.31.3,<0.32.0 in /usr/local/lib/python2.7/dist-packages/SQLAlchemy_Utils-0.31.6-py2.7.egg (from caravel)
Requirement already satisfied (use --upgrade to upgrade): sqlparse>=0.1.16,<0.2.0 in /usr/local/lib/python2.7/dist-packages/sqlparse-0.1.19-py2.7.egg (from caravel)
Downloading/unpacking werkzeug>=0.11.2,<0.12.0 (from caravel)
  Downloading Werkzeug-0.11.5-py2.py3-none-any.whl (305kB): 305kB downloaded
Downloading/unpacking Mako (from alembic>=0.8.5,<0.9.0->caravel)
  Downloading Mako-1.0.4.tar.gz (574kB): 574kB downloaded
  Running setup.py (path:/tmp/pip_build_root/Mako/setup.py) egg_info for package Mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Downloading/unpacking python-editor>=0.3 (from alembic>=0.8.5,<0.9.0->caravel)
  Downloading python-editor-0.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/python-editor/setup.py) egg_info for package python-editor
    
Downloading/unpacking idna>=2.0 (from cryptography>=1.1.1,<2.0.0->caravel)
  Downloading idna-2.1-py2-none-any.whl (54kB): 54kB downloaded
Downloading/unpacking pyasn1>=0.1.8 (from cryptography>=1.1.1,<2.0.0->caravel)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1.1,<2.0.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1.1,<2.0.0->caravel)
Downloading/unpacking enum34 (from cryptography>=1.1.1,<2.0.0->caravel)
  Downloading enum34-1.1.2.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/tmp/pip_build_root/enum34/setup.py) egg_info for package enum34
    
Downloading/unpacking ipaddress (from cryptography>=1.1.1,<2.0.0->caravel)
  Downloading ipaddress-1.0.16-py27-none-any.whl
Downloading/unpacking cffi>=1.4.1 (from cryptography>=1.1.1,<2.0.0->caravel)
  Downloading cffi-1.5.2.tar.gz (388kB): 388kB downloaded
  Running setup.py (path:/tmp/pip_build_root/cffi/setup.py) egg_info for package cffi
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    
Downloading/unpacking colorama>=0.3 (from flask-appbuilder>=1.6.0,<2.0.0->caravel)
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Downloading/unpacking click>=3.0 (from flask-appbuilder>=1.6.0,<2.0.0->caravel)
  Downloading click-6.4-py2.py3-none-any.whl (70kB): 70kB downloaded
Downloading/unpacking Flask-BabelPkg>=0.9.4 (from flask-appbuilder>=1.6.0,<2.0.0->caravel)
  Downloading Flask-BabelPkg-0.9.6.tar.gz
  Running setup.py (path:/tmp/pip_build_root/Flask-BabelPkg/setup.py) egg_info for package Flask-BabelPkg
    
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking Flask-Login==0.2.11 (from flask-appbuilder>=1.6.0,<2.0.0->caravel)
  Downloading Flask-Login-0.2.11.tar.gz
  Running setup.py (path:/tmp/pip_build_root/Flask-Login/setup.py) egg_info for package Flask-Login
    
Downloading/unpacking Flask-OpenID>=1.1.0 (from flask-appbuilder>=1.6.0,<2.0.0->caravel)
  Downloading Flask-OpenID-1.2.5.tar.gz (43kB): 43kB downloaded
  Running setup.py (path:/tmp/pip_build_root/Flask-OpenID/setup.py) egg_info for package Flask-OpenID
    
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'example'
    warning: no previously-included files matching '*.pyo' found under directory 'example'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Requirement already satisfied (use --upgrade to upgrade): Flask-WTF>=0.9.1 in /usr/local/lib/python2.7/dist-packages (from flask-appbuilder>=1.6.0,<2.0.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from flask>=0.10.1,<1.0.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/lib/python2.7/dist-packages (from flask>=0.10.1,<1.0.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /usr/local/lib/python2.7/dist-packages (from pandas==0.18.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.9.2 in /usr/lib/python2.7/dist-packages (from Mako->alembic>=0.8.5,<0.9.0->caravel)
Downloading/unpacking pycparser (from cffi>=1.4.1->cryptography>=1.1.1,<2.0.0->caravel)
  Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pycparser/setup.py) egg_info for package pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Downloading/unpacking Babel>=1.0 (from Flask-BabelPkg>=0.9.4->flask-appbuilder>=1.6.0,<2.0.0->caravel)
  Downloading Babel-2.2.0-py2.py3-none-any.whl (6.5MB): 6.5MB downloaded
Downloading/unpacking speaklater>=1.2 (from Flask-BabelPkg>=0.9.4->flask-appbuilder>=1.6.0,<2.0.0->caravel)
  Downloading speaklater-1.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/speaklater/setup.py) egg_info for package speaklater
    
Downloading/unpacking python-openid>=2.0 (from Flask-OpenID>=1.1.0->flask-appbuilder>=1.6.0,<2.0.0->caravel)
  Downloading python-openid-2.2.5.tar.gz (301kB): 301kB downloaded
  Running setup.py (path:/tmp/pip_build_root/python-openid/setup.py) egg_info for package python-openid
    
    warning: no files found matching 'CHANGELOG'
    warning: no files found matching '*.css' under directory 'doc'
    warning: no files found matching '*.html' under directory 'doc'
Installing collected packages: cryptography, gunicorn, python-dateutil, requests, werkzeug, Mako, python-editor, idna, pyasn1, enum34, ipaddress, cffi, colorama, click, Flask-BabelPkg, Flask-Login, Flask-OpenID, pycparser, Babel, speaklater, python-openid
  Running setup.py install for cryptography
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip_build_root/cryptography/setup.py", line 335, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 827, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1072, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1084, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 640, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 670, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 853, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1081, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1069, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-f9yCjR-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

 #include <ffi.h>

                 ^

compilation terminated.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/cryptography/setup.py", line 335, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs

    replace_conflicting=True,

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 827, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1072, in best_match

    return self.obtain(req, installer)

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1084, in obtain

    return installer(requirement)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 640, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 670, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 853, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1081, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1069, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-f9yCjR-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /home/silverstone/.pip/pip.log
```

**Comment by mistercrunch** [comment]
Thanks for reporting this issue, I just added a section to the docs here:
https://github.com/airbnb/caravel/commit/7b111b790e7e896778fe538f825c28b4306e3d82

It's here already too:
http://airbnb.io/caravel/installation.html
