### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by isublimity** [airbnb/caravel#235]
Find some bug, if i create "Time Series - Line Chart"  and use "Group by" - field containing Russian utf-8 chars i get error "UnicodeEncodeError", but if create simple "pivot table" all OK.  

```javascript
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/caravel-0.8.4-py2.7.egg/caravel/models.py", line 1110, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/caravel-0.8.4-py2.7.egg/caravel/views.py", line 450, in explore
    raise e
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

Screens : http://take.ms/xFrTJ http://take.ms/zUzrj

Sorry my eng)

**Comment by mistercrunch** [comment]
Oh no! Unicode errors... Until we iron that out, can you try on python3 by any chance?

**Comment by isublimity** [comment]
Я нашел решение моей проблемы, в файле 
https://github.com/airbnb/caravel/blob/master/caravel/viz.py#L702

`name = ["{}".format(s) for s in name]`

Заменил на 
`name = ["{}".format(s.encode('utf-8')) for s in name]`


Я первый раз программирую на питоне, могу сильно ошибаться ;)

**Comment by mistercrunch** [comment]
I think this is fixed now with the `from __future__ import unicode_literals` I sprinkled on all files
