### ISSUE TITLE
Unable to add postgres database as datasource

### ISSUE THREAD

**Issue by armed** [airbnb/caravel#252]
OS: Mac OS X 10.11.4
Python: 2.7.10
PostgreSQL: 9.5

My database has about 600 tables per schema. Every schema have same tables as other schemas but with different data. This error did not occur on simple database with only one schema. `Test Connection` button shows ok, but `Save` button caused following error:

```
2016-04-04 13:13:22,400:ERROR:flask_appbuilder.models.sqla.interface:Add record error: (exceptions.AttributeError) 'EntryPoint' object has no attribute 'resolve' [SQL: u'INSERT INTO dbs (created_on, changed_on, database_name, sqlalchemy_uri, password, cache_timeout, changed_by_fk, created_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: [{'cache_timeout': 6000, 'database_name': u'My Test DB', 'password': u'lmuser', 'sqlalchemy_uri': 'postgresql://lm_user_7262:XXXXXXXXXX@localhost/ktsw'}]]
Traceback (most recent call last):
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/flask_appbuilder/models/sqla/interface.py", line 283, in add
    self.session.commit()
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/default.py", line 584, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy/sql/type_api.py", line 978, in process
    return impl_processor(process_param(value, dialect))
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy_utils/types/encrypted.py", line 237, in process_bind_param
    self._update_key()
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy_utils/types/encrypted.py", line 232, in _update_key
    self.engine._update_key(key)
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/sqlalchemy_utils/types/encrypted.py", line 34, in _update_key
    digest = hashes.Hash(hashes.SHA256(), backend=default_backend())
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Users/armed/Library/Python/2.7/lib/python/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
StatementError: (exceptions.AttributeError) 'EntryPoint' object has no attribute 'resolve' [SQL: u'INSERT INTO dbs (created_on, changed_on, database_name, sqlalchemy_uri, password, cache_timeout, changed_by_fk, created_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: [{'cache_timeout': 6000, 'database_name': u'My Test DB', 'password': u'lmuser', 'sqlalchemy_uri': 'postgresql://lm_user_7262:XXXXXXXXXX@localhost/ktsw'}]]
```

**Comment by ariepratama** [comment]
@armed I think this is covered in https://github.com/airbnb/caravel/issues/217, currently in progress to support multiple schema on postgres as well as redshift

**Comment by armed** [comment]
@ariepratama thanks for quick reply. I hope you are right.
I created this issue because I didn't find strange (for me) exception message (`StatementError: (exceptions.AttributeError) 'EntryPoint' object has no attribute 'resolve'`) in issues of this project and maybe there might be another reason for this error.

**Comment by ariepratama** [comment]
oh wait, sorry, I think I've misunderstood your problem, your problem was not able to save into caravel metadata db, not querying to different schema on other database.

**Comment by pedrocicoleme** [comment]
Unfortunately I'm having the same problem, it looks like Caravel is trying to save metadata on the datasource db instead of the correct metadata db defined in `caravel_config.py`.

**Comment by armed** [comment]
Error disappeared after I upgraded `setup_tools` on my mac (as written in this doc: https://pypi.python.org/pypi/setuptools#unix-including-mac-os-x-curl) and reinstalled `cryptography`.

**Comment by mistercrunch** [comment]
Yeah this is clearly related to the `cryptography` library not being installed properly.

**Comment by roymondliao** [comment]
I have the same problem after clicking save button and my database is mysql. The error is as same as "ERROR:flask_appbuilder.models.sqla.interface:Add record error: (exceptions.AttributeError) 'EntryPoint' object has no attribute 'resolve' "

**Comment by ideaplat** [comment]
I have the same problem after clicking save button and my database is mysql. The error is as same as "ERROR:flask_appbuilder.models.sqla.interface:Add record error: (exceptions.AttributeError) 'EntryPoint' object has no attribute 'resolve' "

**Comment by ideaplat** [comment]
i know,just to do :
 pip install cryptography==1.2.1
of course, my system is ubuntu 14.04.
