### ISSUE TITLE
load_examples no such table: css_templates

### ISSUE THREAD

**Issue by mbcheikh** [airbnb/caravel#293]
Following the doc, I installed caravel without problems. When I tried to run the examples I received the error "no such table: css_templates" from sqlalchemy:
```
(env)mb@pb:~/caravel$ caravel load_examples
/home/mb/caravel/env/local/lib/python2.7/site-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
2016-04-08 01:42:40,781:INFO:flask_appbuilder.base:Registering class MyIndexView on menu 
2016-04-08 01:42:40,784:INFO:flask_appbuilder.base:Registering class UtilView on menu 
2016-04-08 01:42:40,786:INFO:flask_appbuilder.base:Registering class LocaleView on menu 
2016-04-08 01:42:40,789:INFO:flask_appbuilder.base:Registering class ResetPasswordView on menu 
2016-04-08 01:42:40,798:INFO:flask_appbuilder.base:Registering class ResetMyPasswordView on menu 
2016-04-08 01:42:40,805:INFO:flask_appbuilder.base:Registering class UserInfoEditView on menu 
2016-04-08 01:42:40,813:INFO:flask_appbuilder.base:Registering class AuthDBView on menu 
2016-04-08 01:42:40,818:INFO:flask_appbuilder.base:Registering class UserDBModelView on menu List Users
2016-04-08 01:42:40,843:INFO:flask_appbuilder.base:Registering class RoleModelView on menu List Roles
2016-04-08 01:42:40,865:INFO:flask_appbuilder.base:Registering class UserStatsChartView on menu User's Statistics
2016-04-08 01:42:40,882:INFO:flask_appbuilder.base:Registering class PermissionModelView on menu Base Permissions
2016-04-08 01:42:40,899:INFO:flask_appbuilder.base:Registering class ViewMenuModelView on menu Views/Menus
2016-04-08 01:42:40,917:INFO:flask_appbuilder.base:Registering class PermissionViewModelView on menu Permission on Views/Menus
2016-04-08 01:42:41,278:INFO:flask_appbuilder.base:Registering class TableColumnInlineView on menu 
2016-04-08 01:42:41,294:INFO:flask_appbuilder.base:Registering class DruidColumnInlineView on menu 
2016-04-08 01:42:41,308:INFO:flask_appbuilder.base:Registering class SqlMetricInlineView on menu 
2016-04-08 01:42:41,324:INFO:flask_appbuilder.base:Registering class DruidMetricInlineView on menu 
2016-04-08 01:42:41,338:WARNING:flask_appbuilder.models.filters:Filter type not supported for column: password
2016-04-08 01:42:41,339:INFO:flask_appbuilder.base:Registering class DatabaseView on menu Databases
2016-04-08 01:42:41,363:INFO:flask_appbuilder.base:Registering class TableModelView on menu Tables
2016-04-08 01:42:41,387:INFO:flask_appbuilder.base:Registering class DruidClusterModelView on menu Druid Clusters
2016-04-08 01:42:41,411:INFO:flask_appbuilder.base:Registering class SliceModelView on menu Slices
2016-04-08 01:42:41,431:INFO:flask_appbuilder.base:Registering class SliceAsync on menu 
2016-04-08 01:42:41,446:INFO:flask_appbuilder.base:Registering class DashboardModelView on menu Dashboards
2016-04-08 01:42:41,466:INFO:flask_appbuilder.base:Registering class DashboardModelViewAsync on menu 
2016-04-08 01:42:41,481:INFO:flask_appbuilder.base:Registering class LogModelView on menu Action Log
2016-04-08 01:42:41,504:INFO:flask_appbuilder.base:Registering class DruidDatasourceModelView on menu Druid Datasources
2016-04-08 01:42:41,527:INFO:flask_appbuilder.base:Registering class R on menu 
2016-04-08 01:42:41,530:INFO:flask_appbuilder.base:Registering class Caravel on menu 
2016-04-08 01:42:41,559:INFO:flask_appbuilder.base:Registering class CssTemplateModelView on menu CSS Templates
Loading examples into <SQLA engine='sqlite:////tmp/caravel.db'>
Creating default CSS templates
Traceback (most recent call last):
  File "/home/mb/caravel/env/bin/caravel", line 94, in <module>
    manager.run()
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/mb/caravel/env/bin/caravel", line 62, in load_examples
    data.load_css_templates()
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/caravel/data/__init__.py", line 350, in load_css_templates
    obj = db.session.query(CSS).filter_by(template_name='Flat').first()
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/mb/caravel/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: css_templates [SQL: u'SELECT css_templates.created_on AS css_templates_created_on, css_templates.changed_on AS css_templates_changed_on, css_templates.id AS css_templates_id, css_templates.template_name AS css_templates_template_name, css_templates.css AS css_templates_css, css_templates.changed_by_fk AS css_templates_changed_by_fk, css_templates.created_by_fk AS css_templates_created_by_fk \nFROM css_templates \nWHERE css_templates.template_name = ?\n LIMIT ? OFFSET ?'] [parameters: ('Flat', 1, 0)]
```

**Comment by sid88in** [comment]
@mbcheikh please check your db settings. Did your permission tables got created in sql lite db properly? You might check with sql lite pro.

**Comment by mistercrunch** [comment]
Yeah looks like you never ran (successfully) `caravel db update` please go through the installation docs again... I you can't run `caravel db update` please open another issue

**Comment by jonchurch** [comment]
`caravel update` didnt work for me but `caravel upgrade` fixed the issue for me.
