### ISSUE TITLE
Timeseries chart on redshift

### ISSUE THREAD

**Issue by yml** [airbnb/caravel#348]
Looks like the chart engine is unhappy with the `timestamp without time zone` col from redshift

```
Traceback (most recent call last):
  File "/srv/virtualenvs/noodleenv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/virtualenvs/noodleenv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/srv/virtualenvs/noodleenv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/virtualenvs/noodleenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/virtualenvs/noodleenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/virtualenvs/noodleenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/virtualenvs/noodleenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/virtualenvs/noodleenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/virtualenvs/noodleenv/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/srv/virtualenvs/noodleenv/src/caravel/caravel/models.py", line 1162, in wrapper
    return f(*args, **kwargs)
  File "/srv/virtualenvs/noodleenv/src/caravel/caravel/views.py", line 501, in explore
    raise e
Exception: Datetime column not provided as part table configuration and is required by this type of chart
```

Shouldn't I be able to use them in time series chart ?

**Comment by mistercrunch** [comment]
I'm curious where this error is showing up, is the web page looking ok and this is coming from the web server logs?

If so, I think you might just have to check the `is_dttm` checkbox in the table's column matrix. The screen that looks like this:
http://airbnb.io/caravel/_images/matrix.png

**Comment by mistercrunch** [comment]
This PR should help filling up that matrix with good default based on types:
https://github.com/airbnb/caravel/pull/353

**Comment by yml** [comment]
My mistake. I got confused by the fact that `birth_name` example table does not have columns checked as `is_dttm`. It is defined on the first tab (Edit Sqla Table > detail) in the field called `Main Dttm Col`

![datetime_example_screenshot from 2016-04-15 09 43 17](https://cloud.githubusercontent.com/assets/125902/14554949/2b90dfb6-02f0-11e6-85b8-a43305523c13.png)
