### ISSUE TITLE
Exploring table gives IOERROR IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by maresk** [airbnb/caravel#389]
Getting this error when trying to explore a table (redirected while trying to create a slice). Default example tables like the `birth_names` and other tables also show this error at route

http://localhost:8088/caravel/explore/table/1/

```IOError
IOError: [Errno 5] Input/output error

Traceback (most recent call last)
File "/home/getafix/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/home/getafix/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/getafix/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/getafix/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/home/getafix/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/getafix/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/getafix/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/home/getafix/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/user/anaconda2/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
return f(self, *args, **kwargs)
File "/home/user/anaconda2/lib/python2.7/site-packages/caravel/models.py", line 1164, in wrapper
return f(*args, **kwargs)
File "/home/user/anaconda2/lib/python2.7/site-packages/caravel/views.py", line 528, in explore
template, viz=obj, slice=slc, datasources=datasources)
File "/home/user/anaconda2/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 157, in render_template
return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
File "/home/user/anaconda2/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
context, ctx.app)
File "/home/user/anaconda2/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
rv = template.render(context)
File "/home/user/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
return self.environment.handle_exception(exc_info, True)
File "/home/user/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/user/anaconda2/lib/python2.7/site-packages/caravel/templates/caravel/explore.html", line 1, in top-level template code
{% extends "caravel/basic.html" %}
File "/home/user/anaconda2/lib/python2.7/site-packages/caravel/templates/caravel/basic.html", line 28, in top-level template code
{% block body %}
File "/home/user/anaconda2/lib/python2.7/site-packages/caravel/templates/caravel/explore.html", line 117, in block "body"
{{ panofield(fieldname) }}
File "/home/user/anaconda2/lib/python2.7/site-packages/caravel/templates/caravel/explore.html", line 24, in template
{{ field(class_=form.field_css_classes(field.name)) }}
File "/home/user/anaconda2/lib/python2.7/site-packages/caravel/forms.py", line 92, in field_css_classes
print(fieldname, self.css_classes[fieldname])
IOError: [Errno 5] Input/output error
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object```

**Comment by mistercrunch** [comment]
That particular line has been removed from master already. Will be fixed in the next release.
