### ISSUE TITLE
Error on installing Caravel.

### ISSUE THREAD

**Issue by Frituurpanda** [airbnb/caravel#448]
Hi,

I'm running a digialocean ubuntu instance and i'm trying to install Caravel on it.

When running: pip install caravel
I get:
Collecting caravel
  Downloading caravel-0.8.9.tar.gz (32.0MB)
    99% |████████████████████████████████| 32.0MB 33.4MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 577, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 871, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 595, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 563, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 552, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 344, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/controller.py", line 224, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/serialize.py", line 81, in dumps
    ).encode("utf8"),
MemoryError

I also get this error on raspberry based system which is strange as i had it running a few hours earlier before I had this error. 

Any thoughts?

**Comment by andrewhn** [comment]
Looks like you're running out of ram. It might only happen sometimes as other processes may or may not be using memory. To find out what's using your memory, you can use the command `top`, followed by `F`, arrow keys to highlight %MEM, then `s` and `q` to set the sort and quit the menu.

**Comment by Frituurpanda** [comment]
Hi andrewhn,

Thanks for the response. On first hand i thought this might be the error. In htop however it seems like my system is only using half of my ram available. I'm going to try to reduce my memory footprint and see what happens then. Does anyone know how much ram Caravel needs at this point?

Thanks.
