### ISSUE TITLE
Can't install Caravel on OSX 10.11.3

### ISSUE THREAD

**Issue by VeenitShah** [airbnb/caravel#461]
I'm trying to install caravel by doing a `pip install caravel`. I get the below error - 

----------------------------------------
Cleaning up...
  Removing temporary dir /private/tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/cffi
Exception information:
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "//anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "//anaconda/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "//anaconda/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "//anaconda/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/cffi

**Comment by mistercrunch** [comment]
Looks like you paste the "cleaning up" part of the log. Cleaning up happens after the error occurs.

**Comment by VeenitShah** [comment]
My bad. I did a re-run. Here is what I got - 

    running install_egg_info
    Copying alembic.egg-info to //anaconda/lib/python2.7/site-packages/alembic-0.8.6-py2.7.egg-info
    running install_scripts
    Installing alembic script to //anaconda/bin
    writing list of installed files to '/tmp/pip-7Znjkz-record/install-record.txt'
  ```
Could not find .egg-info directory in install record for alembic>=0.8.5,<0.9.0 (from caravel)
  Running setup.py install for cryptography
    Running command //anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-89BCYK-record/install-record.txt --single-version-externally-managed --compile
    _configtest.c:1:1: error: thread-local storage is not supported for the current target
    __thread int some_threadlocal_variable_42;
    ^
    1 error generated.
    Note: will not use '__thread' in the C code
    The above error message can be safely ignored
    c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found
    #include <ffi.h>
             ^
    1 error generated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip_build_root/cryptography/setup.py", line 335, in <module>
        **keywords_with_side_effects(sys.argv)
      File "//anaconda/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 269, in __init__
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
      File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 827, in resolve

      File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1072, in best_match

      File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1084, in obtain

      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 380, in fetch_build_egg
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 670, in install_item
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 853, in install_eggs
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1081, in build_and_install
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1069, in run_setup
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    Complete output from command //anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-89BCYK-record/install-record.txt --single-version-externally-managed --compile:
    _configtest.c:1:1: error: thread-local storage is not supported for the current target

__thread int some_threadlocal_variable_42;

^
1 error generated.

Note: will not use '__thread' in the C code

The above error message can be safely ignored

c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found

#include <ffi.h>

         ^

1 error generated.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/private/tmp/pip_build_root/cryptography/setup.py", line 335, in <module>

    **keywords_with_side_effects(sys.argv)

  File "//anaconda/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 269, in __init__

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs

  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 827, in resolve



  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1072, in best_match
  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1084, in obtain



  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 380, in fetch_build_egg

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 670, in install_item

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 853, in install_eggs

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1081, in build_and_install

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1069, in run_setup

distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
  Removing temporary dir /private/tmp/pip_build_root...
Command //anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-89BCYK-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/cryptography
Exception information:
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "//anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "//anaconda/lib/python2.7/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "//anaconda/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command //anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-89BCYK-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/cryptography

```

**Comment by VeenitShah** [comment]
@mistercrunch Any thoughts?

**Comment by andrewhn** [comment]
try `brew install libffi` and re-install

From https://github.com/blockstack/blockstack-profiles-py/blob/master/troubleshooting.md

**Comment by VeenitShah** [comment]
I did a `brew install libffi`. Here is the output - 

```
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.0.13.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libffi-3.0.13.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Some formulae require a newer version of libffi.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libffi/lib

==> Summary
🍺  /usr/local/Cellar/libffi/3.0.13: 15 files, 374.6K
```

Assuming that it's successfully installed, I still get this after the command `pip install caravel` 

```
Installing collected packages: cryptography, flask-appbuilder, Flask-BabelPkg, flask-cache, flask-migrate, flask-script, flask-sqlalchemy, flask-testing, humanize, gunicorn, markdown, pandas, parsedatetime, pydruid, python-dateutil, sqlalchemy, sqlalchemy-utils, sqlparse, werkzeug, Mako, python-editor, idna, enum34, ipaddress, cffi, colorama, click, Flask-Login, Flask-OpenID, Flask-WTF, speaklater, python-openid, WTForms
  Running setup.py install for cryptography
    _configtest.c:1:1: error: thread-local storage is not supported for the current target
    __thread int some_threadlocal_variable_42;
    ^
    1 error generated.
    Note: will not use '__thread' in the C code
    The above error message can be safely ignored
    c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found
    #include <ffi.h>
             ^
    1 error generated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jv/2lyt04497zg1bqzf5904bj9h7c_gv8/T/pip_build_e22654/cryptography/setup.py", line 335, in <module>
        **keywords_with_side_effects(sys.argv)
      File "//anaconda/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 269, in __init__
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
      File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 827, in resolve
    
      File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1072, in best_match
    
      File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1084, in obtain
    
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 380, in fetch_build_egg
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 670, in install_item
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 853, in install_eggs
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1081, in build_and_install
      File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1069, in run_setup
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    Complete output from command //anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/jv/2lyt04497zg1bqzf5904bj9h7c_gv8/T/pip_build_e22654/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jv/2lyt04497zg1bqzf5904bj9h7c_gv8/T/pip-DDnY9x-record/install-record.txt --single-version-externally-managed --compile:
    _configtest.c:1:1: error: thread-local storage is not supported for the current target

__thread int some_threadlocal_variable_42;

^

1 error generated.

Note: will not use '__thread' in the C code

The above error message can be safely ignored

c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found

#include <ffi.h>

         ^

1 error generated.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/private/var/folders/jv/2lyt04497zg1bqzf5904bj9h7c_gv8/T/pip_build_e22654/cryptography/setup.py", line 335, in <module>

    **keywords_with_side_effects(sys.argv)

  File "//anaconda/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 269, in __init__

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs

  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 827, in resolve



  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1072, in best_match



  File "build/bdist.macosx-10.5-x86_64/egg/pkg_resources/__init__.py", line 1084, in obtain



  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/dist.py", line 380, in fetch_build_egg

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 670, in install_item

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 853, in install_eggs

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1081, in build_and_install

  File "build/bdist.macosx-10.5-x86_64/egg/setuptools/command/easy_install.py", line 1069, in run_setup

distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command //anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/jv/2lyt04497zg1bqzf5904bj9h7c_gv8/T/pip_build_e22654/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jv/2lyt04497zg1bqzf5904bj9h7c_gv8/T/pip-DDnY9x-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/jv/2lyt04497zg1bqzf5904bj9h7c_gv8/T/pip_build_e22654/cryptography
Storing debug log for failure in /Users/e22654/.pip/pip.log

```

Am I supposed to change any build variables before re-installing caravel?

**Comment by VeenitShah** [comment]
I just got it to working. Here is what I did - 

```
brew install pkg-config libffi openssl python
env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography
```

The `pip install cryptography` did not work. But, I did a `conda install cryptography` instead and got it set up.

After that, it was just `pip install caravel`
