### ISSUE TITLE
fail to install caravel

### ISSUE THREAD

**Issue by vgromakowski** [airbnb/caravel#467]
Hi,
I cannot acheive installing caravel on centos 7 using pip

`Building wheels for collected packages: cryptography, pandas
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7nCltq/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpApEwg7pip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-7nCltq/cryptography/setup.py", line 335, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
      _Distribution.__init__(self,attrs)
    File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
      self.finalize_options()
    File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
      ep.load()(self, ep.name, value)
    File "/usr/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 161, in cffi_modules
      add_cffi_module(dist, cffi_module)
    File "/usr/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
      execfile(build_file_name, mod_vars)
    File "/usr/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 24, in execfile
      exec(code, glob, glob)
    File "src/_cffi_src/build_openssl.py", line 93, in <module>
      extra_link_args=extra_link_args(compiler_type()),
    File "/tmp/pip-build-7nCltq/cryptography/src/_cffi_src/utils.py", line 64, in build_ffi_for_binding
      extra_link_args=extra_link_args,
    File "/tmp/pip-build-7nCltq/cryptography/src/_cffi_src/utils.py", line 72, in build_ffi
      ffi = FFI()
    File "/usr/lib/python2.7/site-packages/cffi/api.py", line 59, in __init__
      "version mismatch, %s != %s" % (backend.__version__, __version__)
  AssertionError: version mismatch, 0.8.6 != 1.6.0`

As I understand it's a problem with the version of cffi package but I don't know how to upgrade or downgrade it ?

**Comment by vgromakowski** [comment]
maybe we can close the issue as I should have posted it on google group
