### ISSUE TITLE
After creating a new table in caravel,  from mysql, caravel keeps giving "Data too long for column 'type' at row 1"

### ISSUE THREAD

**Issue by shashanksingh** [airbnb/caravel#471]
-----------------------
Caravel 0.9.0
-----------------------

How to recreate

1. After setting Mysql ( Ver 14.14 Distrib 5.7.10 ) as source in http://127.0.0.1:8088/databaseview/add
2. Added a table "daily_inventory_details" in http://127.0.0.1:8088/tablemodelview/add
3. Caused the error screenshot attached.
<img width="1280" alt="screen shot 2016-05-14 at 10 04 46 pm" src="https://cloud.githubusercontent.com/assets/60755/15269552/0c11b542-1a20-11e6-9303-31bbfbb561a0.png">

`2016-05-14 21:06:15,168:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:06:15] "GET /tablemodelview/add HTTP/1.1" 200 -
2016-05-14 21:06:19,730:ERROR:root:(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.DataError) (1406, "Data too long for column 'type' at row 1") [SQL: u'INSERT INTO table_columns (created_on, changed_on, table_id, column_name, verbose_name, is_dttm, is_active, type, groupby, count_distinct, sum, max, min, filterable, expression, description, changed_by_fk, created_by_fk) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2016, 5, 14, 21, 6, 19, 727486), datetime.datetime(2016, 5, 14, 21, 6, 19, 727498), 12L, 'comments', None, 0, 1, 'VARCHAR(255) COLLATE UTF8_UNICODE_CI', 1, 0, 0, 0, 0, 1, '', '', 1L, 1L)]
Traceback (most recent call last):
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/caravel/views.py", line 259, in post_add
    table.fetch_metadata()
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/caravel/models.py", line 809, in fetch_metadata
    db.session.merge(self)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1700, in merge
    self._autoflush()
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1293, in _autoflush
    self.flush()
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
DataError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.DataError) (1406, "Data too long for column 'type' at row 1") [SQL: u'INSERT INTO table_columns (created_on, changed_on, table_id, column_name, verbose_name, is_dttm, is_active, type, groupby, count_distinct, sum, max, min, filterable, expression, description, changed_by_fk, created_by_fk) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2016, 5, 14, 21, 6, 19, 727486), datetime.datetime(2016, 5, 14, 21, 6, 19, 727498), 12L, 'comments', None, 0, 1, 'VARCHAR(255) COLLATE UTF8_UNICODE_CI', 1, 0, 0, 0, 0, 1, '', '', 1L, 1L)]
2016-05-14 21:06:19,779:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:06:19] "POST /tablemodelview/add HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask_appbuilder/views.py", line 397, in add
    widget = self._add()
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 910, in _add
    self.post_add(item)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/caravel/views.py", line 264, in post_add
    "couldn't fetch metadata".format(table.table_name),
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
    value = state._load_expired(state, passive)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 474, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 664, in load_scalar_attributes
    only_load_props=attribute_names)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
    return q.one()
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2693, in one
    ret = list(self)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2749, in _execute_and_instances
    close_with_result=True)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2740, in _connection_from_session
    **kw)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 893, in connection
    execution_options=execution_options)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "/Users/shashanksingh/code/faasos/analytics/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.DataError) (1406, "Data too long for column 'type' at row 1") [SQL: u'INSERT INTO table_columns (created_on, changed_on, table_id, column_name, verbose_name, is_dttm, is_active, type, groupby, count_distinct, sum, max, min, filterable, expression, description, changed_by_fk, created_by_fk) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2016, 5, 14, 21, 6, 19, 727486), datetime.datetime(2016, 5, 14, 21, 6, 19, 727498), 12L, 'comments', None, 0, 1, 'VARCHAR(255) COLLATE UTF8_UNICODE_CI', 1, 0, 0, 0, 0, 1, '', '', 1L, 1L)]
2016-05-14 21:06:19,869:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:06:19] "GET /tablemodelview/add?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2016-05-14 21:06:19,871:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:06:19] "GET /tablemodelview/add?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2016-05-14 21:06:19,873:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:06:19] "GET /tablemodelview/add?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2016-05-14 21:06:19,978:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:06:19] "GET /tablemodelview/add?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2016-05-14 21:06:20,009:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:06:20] "GET /tablemodelview/add?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2016-05-14 21:06:20,186:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:06:20] "GET /tablemodelview/add?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2016-05-14 21:12:47,074:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:12:47] "GET /tablemodelview/list/ HTTP/1.1" 200 -
2016-05-14 21:12:49,661:INFO:werkzeug:127.0.0.1 - - [14/May/2016 21:12:49] "GET /tablemodelview/add HTTP/1.1" 200 -
2016-05-14 21:13:12,449:WARNING:flask_appbuilder.models.sqla.interface:Add record integrity error: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'daily_inventory_details' for key 'table_name'") [SQL: u'INSERT INTO `tables` (created_on, changed_on, table_name, main_dttm_col, description, default_endpoint, database_id, is_featured, user_id, offset, cache_timeout, `schema`, changed_by_fk, created_by_fk) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2016, 5, 14, 21, 13, 12, 445517), datetime.datetime(2016, 5, 14, 21, 13, 12, 445528), 'daily_inventory_details', None, None, '', 2L, 0, None, 0, 10, '', 1L, 1L)]`

**Comment by xrmx** [comment]
Is this still an issue with latest caravel?
