### ISSUE TITLE
Issues with Date JSON Serialization

### ISSUE THREAD

**Issue by JohnOmernik** [airbnb/caravel#486]
I am having an issue where Python reports a circular reference. 

I believe the the issue comes up here:

def json_iso_dttm_ser(obj):
    """
    json serializer that deals with dates
    >>> dttm = datetime(1970, 1, 1)
    >>> json.dumps({'dttm': dttm}, default=json_iso_dttm_ser)
    '{"dttm": "1970-01-01T00:00:00"}'
    """
    if isinstance(obj, datetime):
        obj = obj.isoformat()
    return obj

(in utils.py)

Based on http://stackoverflow.com/questions/14249115/serializing-output-to-json-valueerror-circular-reference-detected 

My data I am querying my data source directly (this is the exact query that caravel is trying to run) I get these results:

trans_day is selected as a dttm column... I am just confused at why this cirucular reference is coming up... 

+-------------+--------+
|  trans_day  |  cnt   |
+-------------+--------+
| 2015-06-02  | 13265  |
| 2015-01-06  | 13031  |
| 2015-05-19  | 12875  |
| 2015-06-16  | 12746  |
| 2015-05-28  | 12724  |
| 2015-05-26  | 12692  |
| 2015-04-21  | 12617  |
| 2015-06-03  | 12410  |
| 2015-05-05  | 12317  |
| 2015-04-07  | 12308  |
+-------------+--------+

The full stack trace is:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/caravel/models.py", line 1294, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/caravel/views.py", line 557, in explore
    payload = obj.get_json()
  File "/usr/local/lib/python2.7/dist-packages/caravel/viz.py", line 269, in get_json
    return self.json_dumps(payload)
  File "/usr/local/lib/python2.7/dist-packages/caravel/viz.py", line 375, in json_dumps
    return json.dumps(obj, default=utils.json_iso_dttm_ser)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected

**Comment by JohnOmernik** [comment]
So it doesn't seem to matter whether the grouped column (trans_day) is marked as dttm column. It has the same error no matter what. So It must be auto detected the YYYY-MM-DD format and trying to do something with it?

**Comment by xrmx** [comment]
Same here with 0.9.0, i got this on a new project when opening the page to create a new slice (http://127.0.0.1:8088/caravel/explore/table/3/)
