### ISSUE TITLE
pandas exception in pandas with 4738b011256c7ea83337aa4e4313c140af05a33c

### ISSUE THREAD

**Issue by xrmx** [airbnb/caravel#673]
I've upgraded caravel to 4738b011256c7ea83337aa4e4313c140af05a33c and on a sunburst slice i get this:

```
Traceback (most recent call last):
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/pandas/core/internals.py", line 3600, in set
    loc = self.items.get_loc(item)
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/pandas/indexes/base.py", line 1985, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'm1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/caravel/views.py", line 799, in explore
    payload = obj.get_json()
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/caravel/viz.py", line 275, in get_json
    'data': self.get_data(),
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/caravel/viz.py", line 1288, in get_data
    ndf['m1'] = df[metric]
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/pandas/core/frame.py", line 2357, in __setitem__
    self._set_item(key, value)
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/pandas/core/frame.py", line 2424, in _set_item
    NDFrame._set_item(self, key, value)
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/pandas/core/generic.py", line 1465, in _set_item
    self._data.set(key, value)
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/pandas/core/internals.py", line 3603, in set
    self.insert(len(self.items), item, value)
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/pandas/core/internals.py", line 3704, in insert
    placement=slice(loc, loc + 1))
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/pandas/core/internals.py", line 2619, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/home/rm/caraveltest/venv/lib/python3.4/site-packages/pandas/core/internals.py", line 90, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 2, placement implies 1
```

**Comment by xrmx** [comment]
Double checked that released 0.9.1 is fine.

**Comment by xrmx** [comment]
Same issue on 0.10.0

**Comment by xrmx** [comment]
If i print df in Sunburst.get_data i see i have a duplicated *count* column.
```
    provincia nazione  count  count
0           0       0  13914  13914
```
