### ISSUE TITLE
When connecting caravel to hive server, throws this error when loading a table

### ISSUE THREAD

**Issue by shkr** [airbnb/caravel#720]
`2016-07-06 19:39:09,153:ERROR:root:Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x10c75d150> can't render element of type <class 'impala.sqlalchemy.STRING'>
Traceback (most recent call last):
  File "/Users/shashank/.virtualenvs/caravel27/lib/python2.7/site-packages/caravel/models.py", line 771, in fetch_metadata
    datatype = "{}".format(col.type).upper()
  File "/Users/shashank/.virtualenvs/caravel27/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 481, in __str__
    return unicode(self.compile()).\
  File "/Users/shashank/.virtualenvs/caravel27/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 468, in compile
    return dialect.type_compiler.process(self)
  File "/Users/shashank/.virtualenvs/caravel27/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 261, in process
    return type_._compiler_dispatch(self, **kw)
  File "/Users/shashank/.virtualenvs/caravel27/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 79, in _compiler_dispatch
    raise exc.UnsupportedCompilationError(visitor, cls)`

Similar issue has been reported here (https://github.com/cloudera/impyla/issues/71), and the exact issue has been posted here (https://github.com/cloudera/impyla/issues/202) however I do not know how to pass `bind=engine` in case of using sqlalchemy via caravel

**Comment by shkr** [comment]
Posted same question with details here http://stackoverflow.com/questions/38237190/when-connecting-caravel-to-hive-server-throws-error-when-loading-a-table

**Comment by wesm** [comment]
It's possible there has been some API change in SQLAlchemy, someone will need to look at https://github.com/cloudera/impyla/blob/master/impala/sqlalchemy.py to see why the error is occurring.

**Comment by shkr** [comment]
The issue was with the package pyhive. I fixed it https://github.com/dropbox/PyHive/commit/896fa9549ecbf5b270974f53eaf2684c4e30002e

**Comment by qinzl1** [comment]
impala have the same problem:
:ERROR:root:Unrecognized data type in qding_report.platform_user_behavior.dt
2017-03-09 17:16:08,564:ERROR:root:Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x7f83fecafe10> can't render element of type <class 'impala.sqlalchemy.STRING'>
