### ISSUE TITLE
OverflowError on World's bank data with caravel running on Windows 7 with Python 2.7

### ISSUE THREAD

**Issue by rusharp** [airbnb/caravel#743]
OverflowError
OverflowError: mktime argument out of range

Traceback (most recent call last)
File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Python27\lib\site-packages\flask_appbuilder\security\decorators.py", line 26, in wraps
return f(self, *args, **kwargs)
File "C:\Python27\lib\site-packages\caravel\models.py", line 1441, in wrapper
return f(*args, **kwargs)
File "C:\Python27\lib\site-packages\caravel\views.py", line 824, in explore
payload = obj.get_json()
File "C:\Python27\lib\site-packages\caravel\viz.py", line 314, in get_json
return self.json_dumps(payload)
File "C:\Python27\lib\site-packages\caravel\viz.py", line 318, in json_dumps
return json.dumps(obj, default=utils.json_int_dttm_ser, ignore_nan=True)
File "C:\Python27\lib\site-packages\simplejson\__init__.py", line 397, in dumps
**kw).encode(obj)
File "C:\Python27\lib\site-packages\simplejson\encoder.py", line 275, in encode
chunks = self.iterencode(o, _one_shot=True)
File "C:\Python27\lib\site-packages\simplejson\encoder.py", line 357, in iterencode
return _iterencode(o, 0)
File "C:\Python27\lib\site-packages\caravel\utils.py", line 312, in json_int_dttm_ser
obj = int(time.mktime(obj.timetuple())) * 1000
OverflowError: mktime argument out of range
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter

**Comment by xrmx** [comment]
This is a dup of https://github.com/airbnb/caravel/issues/721. Please close and subscribe to the other bug
