### ISSUE TITLE
Click on a page　IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by chejinye** [airbnb/caravel#769]
Click on a page, the page content is not loaded, immediately click on the exception a page will report such errors
：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/chejinye/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/chejinye/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 674, in inner
    srv.serve_forever()
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 514, in serve_forever
    HTTPServer.serve_forever(self)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 297, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 230, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/chejinye/anaconda2/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 266, in handle_one_request
    return self.run_wsgi()
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 207, in run_wsgi
    execute(self.server.app)
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 198, in execute
    write(data)
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 158, in write
    self.send_header(key, value)
  File "/home/chejinye/anaconda2/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
@alexism

**Comment by chejinye** [comment]
Traceback (most recent call last):
  File "/home/chejinye/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/chejinye/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 297, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/chejinye/anaconda2/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/chejinye/anaconda2/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/home/chejinye/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 152, in write
    self.send_header(key, value)
  File "/home/chejinye/anaconda2/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

**Comment by shkr** [comment]
I am have same issue

**Comment by chejinye** [comment]
I solved this problem.not use  'caravel runserver -d'  to start,
like this:
nohup gunicorn -w 8 -b 0.0.0.0:8080 caravel:app >> /tmp/caravel.log 2>&1 &

@shkr

**Comment by shkr** [comment]
@chejinye Thank you !

**Comment by mistercrunch** [comment]
I changed the docs to tell people to avoid the dev server (`-d`)
