### ISSUE TITLE
Run unit tests against sqlite and mysql, eventually postgres

### ISSUE THREAD

**Issue by jamescasbon** [airbnb/caravel#78]
```
$ panoramix db upgrade
...
INFO  [alembic.migration] Running upgrade 289ce07647b -> 1a48a5411020, adding slug to dash
Traceback (most recent call last):
  File "/home/james/.local/bin/panoramix", line 374, in <module>
    manager.run()
  File "/home/james/.local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/james/.local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/james/.local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 216, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/james/.local/lib/python2.7/site-packages/alembic/command.py", line 165, in upgrade
    script.run_env()
  File "/home/james/.local/lib/python2.7/site-packages/alembic/script.py", line 390, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/james/.local/lib/python2.7/site-packages/alembic/util.py", line 244, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/james/.local/lib/python2.7/site-packages/alembic/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/home/james/.local/lib/python2.7/site-packages/panoramix/migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "/home/james/.local/lib/python2.7/site-packages/panoramix/migrations/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/home/james/.local/lib/python2.7/site-packages/alembic/environment.py", line 738, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/james/.local/lib/python2.7/site-packages/alembic/migration.py", line 311, in run_migrations
    step.migration_fn(**kw)
  File "/home/james/.local/lib/python2.7/site-packages/panoramix/migrations/versions/1a48a5411020_adding_slug_to_dash.py", line 18, in upgrade
    op.create_unique_constraint('idx_unique_slug', 'dashboards', ['slug'])
  File "<string>", line 7, in create_unique_constraint
  File "/home/james/.local/lib/python2.7/site-packages/alembic/operations.py", line 806, in create_unique_constraint
    schema=schema, **kw)
  File "/home/james/.local/lib/python2.7/site-packages/alembic/ddl/sqlite.py", line 34, in add_constraint
    "No support for ALTER of constraints in SQLite dialect")
NotImplementedError: No support for ALTER of constraints in SQLite dialect

**Comment by mistercrunch** [comment]
Good catch. I just pushed 0.6.1 addressing this. I'm renaming this task to related work that will prevent this.

**Comment by mistercrunch** [comment]
@jamescasbon please confirm that 0.6.1 works for you

**Comment by jamescasbon** [comment]
Yes, worksforme.  Thanks!
