### ISSUE TITLE
Boxplot requires a datetime field

### ISSUE THREAD

**Issue by katemarielewis** [airbnb/caravel#786]
I would like to use the boxplot type of visualization for some data that I have, but it seems like a datetime field is required. Is there a way to allow data that does not have any date or time data to be used?

This is the error that i got:

Datetime column not provided as part table configuration and is required by this type of chart

**Comment by erinshellman** [comment]
Hey, still seeing `is_timeseries = True` on master and encountering the same problem when trying to construct boxplots.

**Comment by JieChenZy** [comment]
Still seeing is_timeseries = True for BoxPlotViz class in viz.py on master. Here is the error when time column is not provided: 

Traceback (most recent call last):
  File "/home/ubuntu/superset_venv_20170420/venv/local/lib/python2.7/site-packages/superset/viz.py", line 234, in get_payload
    df = self.get_df()
  File "/home/ubuntu/superset_venv_20170420/venv/local/lib/python2.7/site-packages/superset/viz.py", line 78, in get_df
    self.results = self.datasource.query(query_obj)
  File "/home/ubuntu/superset_venv_20170420/venv/local/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 538, in query
    qry = self.get_sqla_query(**query_obj)
  File "/home/ubuntu/superset_venv_20170420/venv/local/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 370, in get_sqla_query
    "Datetime column not provided as part table configuration "
Exception: Datetime column not provided as part table configuration and is required by this type of chart
