### ISSUE TITLE
Why table view without group by cannot be used in dashboard?

### ISSUE THREAD

**Issue by Thomasmisfit** [airbnb/caravel#821]
Hi guys,

I met an issue, I want to use Table View to show the table column, I succeed to create slice like this:
![image](https://cloud.githubusercontent.com/assets/8220811/17132618/1d7d8d6a-5355-11e6-8fc4-3f47fc98d675.png)

 But when I use it into the dashboard, I get this error:
![image](https://cloud.githubusercontent.com/assets/8220811/17132573/f318af00-5354-11e6-8605-6b744c63b33a.png)

I found this error will happened no matter what table I use. Is it a bug?

PS: I just followed the doc to install the caravel : http://airbnb.io/caravel/installation.html#caravel-installation-and-initialization

**Comment by xrmx** [comment]
Please paste any exception to get in the caravel logs.

**Comment by Thomasmisfit** [comment]
@xrmx  Here is my logs:

`2016-07-27 01:22:06,420:DEBUG:MARKDOWN:Successfuly imported extension module "markdown.extensions.tables".
2016-07-27 01:22:06,420:DEBUG:MARKDOWN:Successfully loaded extension "markdown.extensions.tables.TableExtension".
2016-07-27 01:22:06,420:DEBUG:MARKDOWN:Successfuly imported extension module "markdown.extensions.fenced_code".
2016-07-27 01:22:06,420:DEBUG:MARKDOWN:Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
2016-07-27 01:22:06,420:DEBUG:MARKDOWN:Successfuly imported extension module "markdown.extensions.codehilite".
2016-07-27 01:22:06,421:DEBUG:MARKDOWN:Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
2016-07-27 01:22:06,962:ERROR:root:'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/caravel/views.py", line 827, in explore
    payload = obj.get_json()
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 294, in get_json
    'data': self.get_data(),
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 414, in get_data
    df = self.get_df()
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 406, in get_df
    df = super(TableViz, self).get_df(query_obj)
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 144, in get_df
    query_obj = self.query_obj()
  File "/usr/local/lib/python2.7/site-packages/caravel/viz.py", line 402, in query_obj
    d['orderby'] = [json.loads(t) for t in fd.get('order_by_cols', [])]
TypeError: 'NoneType' object is not iterable
2016-07-27 01:22:07,047:INFO:root:Caching for the next None seconds
2016-07-27 01:22:07,049:INFO:root:Caching for the next None seconds
2016-07-27 01:22:07,057:INFO:root:Caching for the next None seconds
2016-07-27 01:22:07,133:INFO:root:Caching for the next None seconds
2016-07-27 01:22:07,244:INFO:root:Caching for the next None seconds
2016-07-27 01:22:07,275:INFO:root:Caching for the next None seconds
2016-07-27 01:22:07,359:INFO:root:Caching for the next None seconds
/usr/local/lib/python2.7/site-packages/caravel/viz.py:997: FutureWarning: sort is deprecated, use sort_values(inplace=True) for INPLACE sorting
  dfs.sort(ascending=False)
2016-07-27 01:22:07,507:INFO:root:Caching for the next None seconds
2016-07-27 01:22:07,513:INFO:root:Caching for the next None seconds`

**Comment by rhp4515** [comment]
Duplicate as #812

**Comment by mistercrunch** [comment]
https://github.com/airbnb/caravel/pull/823

**Comment by spspaul** [comment]
For those who continue to run into this exception (like me)
even after getting the fix from #823, you must chose at least
one value for **```Ordering```** under **```NOT GROUPED BY```**
when building the slice or you will run into same exception when
trying to use the slice in a dashboard.

**Comment by kylozw** [comment]
Same issue when download csv in slice.
Choosing one value for `Ordering` under `NOT GROUPED BY` worked.

**Comment by spspaul** [comment]
@kylozw ,

FWIW, ```Ordering``` does not take all columns, just ones of certain types.
What I do in order to:
* satisfy Caravel's need to have at least one value for ```Ordering```
* get things sorted the way I want when using ```NOT GROUPED BY```

I define a view in the database where the first column is defined like so:
```
CREATE OR REPLACE VIEW blar AS
SELECT RANK() OVER (ORDER BY col1, col2, etc) AS order_id,
```
I use then use ```blar``` as Source/Table.
In Caravel/Slice definition, I specify ```order_id``` for ```Ordering```.

Good luck.

**Comment by 521xueweihan** [comment]
Thanks spspaul:  

**Solution:**

you must chose at least
one value for `Ordering` under `NOT GROUPED BY`
