### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by jiamo** [airbnb/caravel#943]
> caravel@0.1.0 dev /home/jiamo/Own/caravel/caravel/assets
    > NODE_ENV=dev webpack -d --watch --colors

    Hash: ba3ea7d8af890096c32c
    Version: webpack 1.13.1
    Time: 22157ms
                    Asset     Size  Chunks             Chunk Names
        common.entry.js.map   747 kB       0  [emitted]  common
            common.entry.js   621 kB       0  [emitted]  common
        dashboard.entry.js  7.17 MB       2  [emitted]  dashboard
        explore.entry.js  5.69 MB       3  [emitted]  explore
            sql.entry.js  2.01 MB       4  [emitted]  sql
        standalone.entry.js  5.06 MB       5  [emitted]  standalone
        welcome.entry.js  1.22 MB       6  [emitted]  welcome
        css-theme.entry.js  10.7 kB       1  [emitted]  css-theme
    css-theme.entry.js.map  12.7 kB       1  [emitted]  css-theme
    dashboard.entry.js.map  8.51 MB       2  [emitted]  dashboard
    explore.entry.js.map  6.83 MB       3  [emitted]  explore
        sql.entry.js.map  2.41 MB       4  [emitted]  sql
    standalone.entry.js.map  6.04 MB       5  [emitted]  standalone
    welcome.entry.js.map  1.49 MB       6  [emitted]  welcome
        + 687 hidden modules

    ERROR in ./~/css-loader!./stylesheets/sql.css
    Module build failed: Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:226:15)
        at new Processor (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:134:25)
        at postcss (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/postcss.js:73:10)
        at processCss (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/processCss.js:150:17)
        at Object.module.exports (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/loader.js:24:2)
    @ ./stylesheets/sql.css 4:14-74

    ERROR in ./~/css-loader!./vendor/pygments.css
    Module build failed: Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:226:15)
        at new Processor (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:134:25)
        at postcss (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/postcss.js:73:10)
        at processCss (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/processCss.js:150:17)
        at Object.module.exports (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/loader.js:24:2)
    @ ./vendor/pygments.css 4:14-79

    ERROR in ./~/css-loader!./stylesheets/dashboard.css
    Module build failed: Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:226:15)
        at new Processor (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:134:25)
        at postcss (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/postcss.js:73:10)
        at processCss (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/processCss.js:150:17)
        at Object.module.exports (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/loader.js:24:2)
    @ ./stylesheets/dashboard.css 4:14-80

    ERROR in ./~/css-loader!./stylesheets/explore.css
    Module build failed: Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:226:15)
        at new Processor (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:134:25)
        at postcss (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/postcss.js:73:10)
        at processCss (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/processCss.js:150:17)
        at Object.module.exports (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/loader.js:24:2)
    @ ./stylesheets/explore.css 4:14-78

    ERROR in ./~/css-loader!./stylesheets/welcome.css
    Module build failed: Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:226:15)
        at new Processor (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:134:25)
        at postcss (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/postcss.js:73:10)
        at processCss (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/processCss.js:150:17)
        at Object.module.exports (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/loader.js:24:2)
    @ ./stylesheets/welcome.css 4:14-78

    ERROR in ./~/css-loader!./~/cal-heatmap/cal-heatmap.css
    Module build failed: Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:226:15)
        at new Processor (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:134:25)
        at postcss (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/postcss.js:73:10)
        at processCss (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/processCss.js:150:17)
        at Object.module.exports (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/loader.js:24:2)
    @ ./~/cal-heatmap/cal-heatmap.css 4:14-69

    ERROR in ./~/css-loader!./~/bootstrap-toggle/css/bootstrap-toggle.min.css
    Module build failed: Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:226:15)
        at new Processor (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:134:25)
        at postcss (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/postcss.js:73:10)
        at processCss (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/processCss.js:150:17)
        at Object.module.exports (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/loader.js:24:2)
    @ ./~/bootstrap-toggle/css/bootstrap-toggle.min.css 4:14-81

    ERROR in ./~/css-loader!./~/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css
    Module build failed: Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:226:15)
        at new Processor (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/processor.js:134:25)
        at postcss (/home/jiamo/Own/caravel/caravel/assets/node_modules/postcss/lib/postcss.js:73:10)
        at processCss (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/processCss.js:150:17)
        at Object.module.exports (/home/jiamo/Own/caravel/caravel/assets/node_modules/css-loader/lib/loader.js:24:2)
    @ ./~/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css 4:14-85

**Comment by jiamo** [comment]
After rm total node_modules and reinstall . It is fine.

**Comment by xrmx** [comment]
Closing then, thanks @jiamo for the update
